### ISSUE TITLE
Auto Post To Twitter not working.. somebody please help 

### ISSUE THREAD

**Issue by PeterDredd** [10up/autoshare-for-twitter#317] opened 2024-03-20 13:11 UTC
### Describe your question

I got the successful notification after finishing the setup.

But after publishing a post.. it doesn’t auto post to my X account. I checked the box that says post to Twitter.. but it still didn’t work. The dot rolls for few seconds and stops. No error message.

I tried disconnecting and reconnecting.. but still it didn’t work. Someone should help out please.. I have a verified twitter account if that means anything.

![IMG_3433](https://github.com/10up/autoshare-for-twitter/assets/164010930/d4ed7d68-b930-4d7f-a4a2-ef1ba22471b9)
![IMG_3434](https://github.com/10up/autoshare-for-twitter/assets/164010930/ac3b050d-473b-4ccd-b223-5fb27b603f80)
![IMG_3411](https://github.com/10up/autoshare-for-twitter/assets/164010930/5a94717c-c471-4fc5-8519-7fb5dc7e5415)
![IMG_3431](https://github.com/10up/autoshare-for-twitter/assets/164010930/aaa98cd7-4d82-4ed5-a730-268e8362844e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment] 2024-03-20 13:14
Closing as duplicate of #315.

**Closed as not planned by jeffpaul** 2024-03-20 13:14 UTC
Labels: type:question
